### ISSUE TITLE
MDN storage investigation: S3 vs EFS

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#183]
[Parent issue](https://github.com/mozmar/infra/issues/147)

Determine the tradeoffs between S3 and EFS for storing and serving files.

More info [here](https://docs.google.com/document/d/1_JtwNQv2zyrVkZ3mLuu3-zEVbrwaVH8ErdDTe4GUy9U/edit#heading=h.88l66nuhk518)

At a high level, we need storage for the following object types:
(highlights taken from the doc above)

- **Bulk uploads**
  - large files, uploaded by staff
  - some need `latest` URL
  - no prod/staging distinction
- **Static assets**
  - js, css, images. 
  - generated by Kuma, 
  - Uploaded via prod push
  - trusted and executable by CSP
  - perf critical (CloudFront)
  - maintain prod/staging/other environments
- **User uploads**
  - MIME types configured in Django Admin (images, fonts, HTML)
  - tracked in MDN DB
  - performance is important, as they are embedded into pages
  - JS allows, served from different domain
  - maintain prod/staging/local environments
  - local attachments work by redirecting to prod file
- **Legacy files**
  - small to large files (vode, no JS/CSS)
  - not updated in 5-10 years
  - no prod/staging distinction
- **Legacy samples**
  - never update == read only
  - requires JS execution, inline CSS etc
  - not considered important for site performance
  - no prod/staging distinction
  - This has been [a target](https://bugzilla.mozilla.org/show_bug.cgi?id=1076893) to move since 2014.

**Comment by metadave** [comment]
@jgmize @jwhitlock The Toronto conversation is a bit foggy to me now, does Kuma need to work to incorporate S3, while EFS could be plugged in without changes?

**Comment by jgmize** [comment]
@metadave yes, we should be able to set up a PVC backed by EFS and use it without changes to the kuma codebase, and it may have some performance advantages as well. I think we should test that first and then decide if the s3 alternative is worth the development effort.

**Comment by jgmize** [comment]
For more context, at the time we originally planned for s3, neither EFS nor k8s PVCs were available.

**Comment by metadave** [comment]
I experimented a bit with EFS, and it worked! 
Here's a crude example of the K8s objects I deployed:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mdn-uploads-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/"
    server: <populate from EFS console>
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mdn-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: mdn-uploads-pv
---
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: mdn-uploads-storage
      persistentVolumeClaim:
       claimName: mdn-uploads-pvc
  containers:
    - name: task-pv-container
      image: nginx
      volumeMounts:
        - mountPath: "/mdn"
          name: mdn-uploads-pvc
  volumes:
    - name: mdn-uploads-pvc
      persistentVolumeClaim:
        claimName: mdn-uploads-pvc
```

After exec'ing bash on the `task-pv-pod`, I was able to write to `/mdn/foo`. I launched a new EC2 instance and was able to see the file.

**Comment by metadave** [comment]
useful notes on EFS [here](https://github.com/open-guides/og-aws#efs-basics)

**Comment by metadave** [comment]
Change the pod to a Deployment w/ 3 replicas, and was easily able to write and see data shared between pods. 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pvtest
  namespace: metadave
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pvtest
    spec:
      volumes:
        - name: mdn-uploads-storage
          persistentVolumeClaim:
          claimName: mdn-uploads-pvc
      containers:
        - name: task-pv-container
          image: nginx
          volumeMounts:
            - mountPath: "/mdn"
              name: mdn-uploads-pvc
      volumes:
        - name: mdn-uploads-pvc
          persistentVolumeClaim:
            claimName: mdn-uploads-pvc
```

**Comment by metadave** [comment]
After some investigation, I'd recommend using EFS as a "drop-in" replacement for Kuma. Investigation notes below.

## S3

While S3 is simple to setup and interact with, there would have to be several changes to the Kuma code to support it, thus slowing down our migration to AWS.

## EFS

[FAQ](https://aws.amazon.com/efs/faq/)

EFS mounted filesystems behave just like other filesystems, so Kuma can continue to read/write against the FS without significant changes. I was able to test a 3 pod deployment, write data in each pod, and read data back. Writes and reads were **NOT** tested for performance characteristics.

### Performance

EFS supports 2 modes: `General Purpose` and `Max I/O`. The default when creating a file system is `General Purpose`. 

From the [EFS FAQ](https://aws.amazon.com/efs/faq/):

```
“General Purpose” performance mode is appropriate for most file systems, and 
is the mode selected by default when you create a file system. “Max I/O” 
performance mode is optimized for applications where tens, hundreds, or 
thousands of EC2 instances are accessing the file system — it scales to
higher levels of aggregate throughput and operations per second with a
tradeoff of slightly higher latencies for file operations.
```

See also: http://docs.aws.amazon.com/efs/latest/ug/limits-throughput.html


### Reclaim policy

Our `PersistentVolume` definitions should ***always*** include `persistentVolumeReclaimPolicy: Retain` in the `spec` section. This means that when a pod is deleted, Kubernetes won't touch EFS.

Here are the reclaim policies from the [K8s volume docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) (docs don't mention what the default is):

```
Current reclaim policies are:
Retain – manual reclamation
Recycle – basic scrub (“rm -rf /thevolume/*”)
Delete – associated storage asset such as AWS EBS, GCE PD, Azure Disk, or OpenStack Cinder volume is deleted

Currently, only NFS and HostPath support recycling. AWS EBS, GCE PD, Azure Disk, and Cinder volumes support deletion.
```

### Locking

From the [EFS FAQ](https://aws.amazon.com/efs/faq/):

```
Locking in Amazon EFS follows the NFSv4.1 protocol for advisory locking, and enables your applications to use both whole file and byte range locks.
```

### Backups:

As a yaml mistake could possibly allow a pod to erase an EFS volume, we should establish periodic backup from EFS to S3 (or even Glacier to save $$$):

- http://docs.aws.amazon.com/efs/latest/ug/efs-backup.html
- https://aws.amazon.com/glacier/


### Availability

From [The Open Guide to Amazon Web Services](https://github.com/open-guides/og-aws#efs):

High availability is achieved by having mount targets in different subnets / availability zones.

![Alt](http://docs.aws.amazon.com/efs/latest/ug/images/overview-flow.png)

### Security

EFS does not provide encryption for data at rest.

### Directory organization

K8s `PersistentVolumes` can choose the directory in EFS to mount, so we don't need to mount the root. If needed, we could create a directory structure similar to the following, and a prod MDN `PersistentVolume` could mount into `/mdn/prod`:

```
.
└── mdn
    ├── attic
    ├── dev
    ├── prod
    │   ├── presentations
    │   ├── samples
    │   └── uploads
    └── stage
```


### Storage sizing

We don't specify a minimum or maximum size up front, EFS can scale automatically to [handle petabytes of data](https://aws.amazon.com/efs/faq/). 

### Configuration

The `Amazon EC2 mount instructions` link (availabile when viewing a configured EFS file system in the AWS console) shows additional mount options that we might have to specify as additional configuration to the `PersistentVolume`.

For example, the directions suggest using the following command to mount EFS from the CLI:

`sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 some_url.efs.us-east-1.amazonaws.com:/ efs`

While the [documentation is vague](https://kubernetes.io/docs/concepts/storage/persistent-volumes/), the `volume.beta.kubernetes.io/mount-options` annotation may help us in specifying additional configuration.

### Multi-region replication

We'll need to have at least 1 EFS file system per region. If uploads occur in a one region, we'll have to replicate data to other regions. Given that the amount of files to written to MDN persistent storage is relatively low, we could use simple tech such as `rsync` in a cron task for replication. 

Additionally, replication guarantees could be relatively lax: we can state that a file could appear in another region after some duration (eg. 15-30 minutes or longer). 

We'll need to ensure that replicating from each region to others is a safe operation.

##### Questions:

- Is there a single cron task that handles pulling/pushing data from/to each region?
  - or does each region have it's own cron task that pushes data out? 
  - My preference is for a single coordinator cront task to keep things simple and help reduce multi-master replication issues.
- Are files immutable when they are uploaded, or are new files/hashes generated as the result of a file change?

### Misc

As mentioned in a previous comment, this site has some great info on most AWS services:

https://github.com/open-guides/og-aws#efs

## TODO

- [ ] create a card to investigate an [EFS backup strategy](http://docs.aws.amazon.com/efs/latest/ug/efs-backup.html
)
- [ ] investigate additional EFS configuration via annotation
- [ ] investigate replication strategy
- [ ] determine if we need a multi-pod performance test against EFS

**Comment by metadave** [comment]
Note: would we consider moving [these newer S3 buckets](https://github.com/mozmar/infra/blob/master/mdn/mdn_infra.tf#L7-L102) to EFS?

**Comment by metadave** [comment]
The annotation for setting additional mount settings works: https://gist.github.com/metadave/9fa6381304bddbc80629a0131360c3ac

**Comment by metadave** [comment]
EFS backup strategy issue: https://github.com/mozmar/infra/issues/189

**Comment by metadave** [comment]
(this is also mentioned in the writeup above)

***EFS is ONLY available in the following regions:***

- EU (Ireland)
- Asia Pacific (Sydney)
- US East (N. Virginia)
- US East (Ohio)
- US West (Oregon)

**Comment by metadave** [comment]
virginia: `fs-1b4cfe52.efs.us-east-1.amazonaws.com`

**Comment by metadave** [comment]
Using this to create the initial dir layout:

```
#!/bin/bash
for rootdir in mdn-dev mdn-stage mdn-prod
do
    mkdir -p $rootdir
    mkdir -p $rootdir/www/diagrams
    mkdir -p $rootdir/www/presentations
    mkdir -p $rootdir/www/samples
    mkdir -p $rootdir/www/uploads
done


```

which gives us this:

```
.
├── mdn-dev
│   └── www
│       ├── diagrams
│       ├── presentations
│       ├── samples
│       └── uploads
├── mdn-prod
│   └── www
│       ├── diagrams
│       ├── presentations
│       ├── samples
│       └── uploads
└── mdn-stage
    └── www
        ├── diagrams
        ├── presentations
        ├── samples
        └── uploads
```

**Comment by metadave** [comment]
I copied `/data/www/diagrams`, `/data/www/presentations`, and `/data/www/samples` from SCL3 to the virginia EFS share. All files use ~2.4G uncompressed. 

They're currently in the `mdn-dev` dir in EFS:

```
root@ip-172-20-57-187:/mdn/mdn-dev/www# ls -la
total 24
drwxr-xr-x  6 root root 4096 Apr 28 18:36 .
drwxr-xr-x  3 root root 4096 Apr 28 15:52 ..
drwxr-xr-x  3 root root 4096 Apr 28 18:42 diagrams
drwxr-xr-x 13 root root 4096 Apr 28 18:36 presentations
drwxr-xr-x 26 root root 4096 Apr 28 18:37 samples
drwxr-xr-x  2 root root 4096 Apr 28 18:28 uploads
```

---

I'm not sure if we can share these between dev/stage/prod environments, as we would have to symlink out of the pvc mount point to a shared directory.

For example:

EFS has:
```
/mdn-dev
/mdn-stage
/mdn-prod
/shared
```
The PVC for an environment will point to one of the 3 `mdn-` directories above (eg `/mdn-dev` is mounted at `/data` in a pod). If we symlinked to an EFS `/shared` dir, the symlink would point outside of the pvc mount point. Do we care about copying 2.4 Gb of files to each environment?

**Comment by metadave** [comment]
closing this as it's just for investigation.

**Comment by metadave** [comment]
@escattone and I would like to split out each environment (dev,stage,prod) into separate EFS instances. This allows us to work on dev/stage PV/PVC stuff without impacting prod instances. 

Filesystem layout would look like this:

```
└── www
    ├── diagrams
    ├── presentations
    ├── samples
    └── uploads
```

```
#!/bin/bash
mkdir -p www/diagrams
mkdir -p www/presentations
mkdir -p www/samples
mkdir -p www/uploads
```
